version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: chat-app-db
    restart: always
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
